* phoebe's super sexy stumpwm config
  my configuration for [[https://stumpwm.github.io][stumpwm]], my window manager of choice.

  to install, do:
  #+BEGIN_SRC sh
  git clone git@github.com:gefjon/stumpwm-init.git ~/quicklisp/local-projects/stumpwm-init
  mkdir -p ~/.stumpwm.d
  ln -s ~/quicklisp/local-projects/stumpwm-init/init.lisp ~/.stumpwm.d/init.lisp
  #+END_SRC
** contrib
   i have [[https://github.com/gefjon/stumpwm-contrib][a fork]] of the [[https://github.com/stumpwm/stumpwm-contrib][stumpwm contrib modules]]. to install them such that this
   configuration can find them, do:
   #+BEGIN_SRC sh
     git clone git@github.com:gefjon/stumpwm-contrib.git ~/quicklisp/local-projects/stumpwm-contrib
   #+END_SRC
** theme
   i use the colors defined by [[https://github.com/dracula/dracula-theme][dracula]]. i also use their themes for emacs and
   xresources. i used to use [[https://github.com/chriskempson/base16][base16]] to manage my themes, but found it overkill;
   i replaced it with a small macro called ~DEFTHEME~ (defined in
   [[file:src/deftheme.lisp][deftheme.lisp]]); i pasted the dracula colors into [[file:src/dracula.lisp][a ~DEFTHEME~ form]], and then
   selected them in [[file:src/theme.lisp][theme.lisp]].
*** setting .Xresources
    clone the dracula xresources repo:
    #+BEGIN_SRC sh
      git clone https://github.com/dracula/xresources.git ~/dracula-xresources
    #+END_SRC
    and symlink it in place:
    #+BEGIN_SRC sh
      ln -s ~/dracula-xresources/Xresources ~/.Xresources
    #+END_SRC
    load it into your current session:
    #+BEGIN_SRC sh
      xrdb --load ~/.Xresources
    #+END_SRC
    once that works, it goes into your userinit, like:
    #+BEGIN_SRC lisp
      (stumpwm:run-shell-command "xrdb -load ~/.Xresources")
    #+END_SRC
*** background
    setting the background uses ~xsetroot~, which for some reason isn't
    preinstalled on manjaro. install it with:
    #+BEGIN_SRC sh
      sudo pacman -Syu xorg-xsetroot
    #+END_SRC
** emacs daemon
   i'm back to using systemd to run emacs. this time, my [[file:~/emacs/etc/emacs.service][emacs.service]] is:
   #+BEGIN_SRC conf
     [Unit]
     Description=Emacs text editor
     Documentation=info:emacs man:emacs(1) https://gnu.org/software/emacs/

     [Service]
     Type=notify
     ExecStart=emacs --fg-daemon
     ExecStop=emacsclient --eval "(kill-emacs)"
     Restart=on-failure
     TimeoutStartSec=infinity

     [Install]
     WantedBy=default.target
   #+END_SRC
   note that ~TimeoutStartSec=infinity~ disables systemd's startup timer
   mechanism, because for some reason on my machine emacs does not signal when
   it's initialized.

   if you're installing fresh, just edit the above directly into the emacs
   source tree & then install & reload with
   #+BEGIN_SRC sh
     sudo make install
     systemctl --user daemon-reload
     systemctl --user enable emacs.service
   #+END_SRC
** brightness
   i use ~brightnessctl~ to manage my laptop's screen brightness. to install
   it:
   #+BEGIN_SRC sh
     sudo pacman -Syu brightnessctl
   #+END_SRC
   you'll need to reboot to make the ~udev~ rules take effect.
